// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Batch
{
    public int BatchId { get; set; }

    public string StartDateTime { get; set; }

    public string EndDateTime { get; set; }

    public int? PhotoLibraryId { get; set; }

    public int? FilesFound { get; set; }

    public int? FilesAdded { get; set; }

    public int? FilesUpdated { get; set; }

    public int? FilesSkipped { get; set; }

    public int? FilesRemoved { get; set; }

    public int? FilesReadError { get; set; }
}