// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Collection
{
    public int CollectionId { get; set; }

    public int ImageId { get; set; }

    public string CollectionName { get; set; }

    public string CollectionUri { get; set; }
}