// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Image
{
    public int ImageId { get; set; }

    public int? PhotoLibraryId { get; set; }

    public int? BatchId { get; set; }

    public string Filepath { get; set; }

    public string Sha1 { get; set; }

    public string Format { get; set; }

    public string Filename { get; set; }

    public string Filesize { get; set; }

    public string FileCreatedDate { get; set; }

    public string FileModifiedDate { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Rating { get; set; }

    public string DateTimeTaken { get; set; }

    public string DateTimeTakenTimeZone { get; set; }

    public string Device { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Altitude { get; set; }

    public string Location { get; set; }

    public string City { get; set; }

    public string StateProvince { get; set; }

    public string Country { get; set; }

    public string CountryCode { get; set; }

    public string Creator { get; set; }

    public string Copyright { get; set; }

    public string Metadata { get; set; }

    public string RecordAdded { get; set; }

    public string RecordModified { get; set; }
}