// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Location
{
    public int LocationId { get; set; }

    public string LocationIdentifier { get; set; }

    public string LocationName { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }
}