// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Log
{
    public int LogEntryId { get; set; }

    public int? BatchId { get; set; }

    public string Datetime { get; set; }

    public string Filepath { get; set; }

    public string Sha1 { get; set; }

    public int? Filesize { get; set; }

    public string Operation { get; set; }
}