// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class MetadataHistory
{
    public int HistoryId { get; set; }

    public int? ImageId { get; set; }

    public string Filepath { get; set; }

    public int? AddedBatchId { get; set; }

    public string RecordAdded { get; set; }

    public int? ModifiedBatchId { get; set; }

    public string RecordModified { get; set; }

    public string Metadata { get; set; }
}