// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class PeopleTag
{
    public int PeopleTagId { get; set; }

    public string PersonName { get; set; }

    public string Fsid { get; set; }
}