// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Person
{
    public int PersonId { get; set; }

    public int? ImageId { get; set; }

    public string PersonName { get; set; }

    public string PersonIdentifier { get; set; }
}