// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class PhotoLibrary
{
    public int PhotoLibraryId { get; set; }

    public string Folder { get; set; }
}