// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Region
{
    public string RegionId { get; set; }

    public int ImageId { get; set; }

    public string RegionName { get; set; }

    public string RegionType { get; set; }

    public string RegionAreaUnit { get; set; }

    public decimal? RegionAreaH { get; set; }

    public decimal? RegionAreaW { get; set; }

    public decimal? RegionAreaX { get; set; }

    public decimal? RegionAreaY { get; set; }

    public decimal? RegionAreaD { get; set; }
}