// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class RelationTag
{
    public int RelationTagId { get; set; }

    public int? ImageId { get; set; }

    public int? TagId { get; set; }
}