// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class RelationPeopleTag
{
    public int PeopleRelationId { get; set; }

    public int? ImageId { get; set; }

    public int? PeopleTagId { get; set; }
}