// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImageDB.Models;

public partial class Tag
{
    public int TagId { get; set; }

    public string TagName { get; set; }

    public int? Source { get; set; }
}